### ISSUE TITLE
Fix all dashboard bug

### ISSUE THREAD

**Issue by 1ouiss** [theo-code33/short-url-app#7]
**TODO**
- [ ] Change variant of error enqueue snackbar
- [x] Fix error message
- [x] Load url and api key on mount page
- [x] Fix refresh data when url or api key are created and when user is updated
- [x] fix copy and open url
